name: CI
on: push

jobs:
  linttest:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Install dependencies
      run: npm i

    - run: npm run lint
    - run: npm test
